name: ETL workflow for Group 1

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/*.R', '**/*.qmd') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr","readr","RSQLite","lubridate","rmarkdown","DBI","kableExtra"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: |
          quarto install tinytex

      - name: Render .qmd file to PDF
        run: |
          quarto render R/data_pipeline_render.qmd --to pdf

      - name: Add files
        run: |
          git config --global user.email "vignesh.parthasarathy@warwick.ac.uk"
          git config --global user.name "Vickyyyy98"
          git add database/ecommerce_database_v1.db
          git add R/data_pipeline_render.pdf

      - name: Commit files
        run: |
          git commit -m "Database and PDF Upload" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
